DIR := $(dir $(lastword $(MAKEFILE_LIST)))


upper_canopy_reinforced-output := $(DIR)upper_canopy_reinforced.stl
upper_canopy_reinforced-input := $(DIR)upper_canopy_reinforced.scad
upper_canopy_reinforced-flags :=

stl-target += upper_canopy_reinforced
