DIR := $(dir $(lastword $(MAKEFILE_LIST)))

glass_bell_base-output := $(DIR)glass_bell_base.stl
glass_bell_base-input := $(DIR)glass_bell_base.scad
glass_bell_base-flags :=

stl-target += glass_bell_base
