DIR := $(dir $(lastword $(MAKEFILE_LIST)))
TEST_NAME := $(lastword $(subst /, ,$(DIR)))

bl_touch_support-output := $(DIR)bl_touch_support.stl
bl_touch_support-input := $(DIR)bl_touch_support.scad
bl_touch_support-flags :=

stl-target += bl_touch_support
