DIR := $(dir $(lastword $(MAKEFILE_LIST)))
TEST_NAME := $(lastword $(subst /, ,$(DIR)))

shutter_crank_hook-output := $(DIR)shutter_crank_hook.stl
shutter_crank_hook-input := $(DIR)shutter_crank_hook.scad
shutter_crank_hook-flags :=

stl-target += shutter_crank_hook
