DECKING_HEIGHT = 27;
DECKING_SPACING = 5;

GUIDE_THICKNESS = 2;
GUIDE_WIDTH = 40;
GUIDE_HEIGHT=35;

$fn = 40;

cube([GUIDE_HEIGHT, GUIDE_WIDTH, GUIDE_THICKNESS]);
translate([0, GUIDE_WIDTH/2 - DECKING_SPACING/2, 0]) cube([GUIDE_HEIGHT, DECKING_SPACING, DECKING_HEIGHT]);