DIR := $(dir $(lastword $(MAKEFILE_LIST)))
TEST_NAME := $(lastword $(subst /, ,$(DIR)))

power_box-output := $(DIR)power_box.stl
power_box-input := $(DIR)power_box.scad
power_box-flags :=

stl-target += power_box
