DIR := $(dir $(lastword $(MAKEFILE_LIST)))
TEST_NAME := $(lastword $(subst /, ,$(DIR)))

fixing_bracket-output := $(DIR)fixing_bracket.stl
fixing_bracket-input := $(DIR)fixing_bracket.scad
fixing_bracket-flags :=

stl-target += fixing_bracket
