DIR := $(dir $(lastword $(MAKEFILE_LIST)))


naze32_mount_9mm-output := $(DIR)naze32_mount_9mm.stl
naze32_mount_9mm-input := $(DIR)naze32_mount_9mm.scad
naze32_mount_9mm-flags :=

stl-target += naze32_mount_9mm
