DIR := $(dir $(lastword $(MAKEFILE_LIST)))
TEST_NAME := $(lastword $(subst /, ,$(DIR)))

tutor_hook-output := $(DIR)tutor_hook.stl
tutor_hook-input := $(DIR)tutor_hook.scad
tutor_hook-flags :=

stl-target += tutor_hook
