DIR := $(dir $(lastword $(MAKEFILE_LIST)))
TEST_NAME := $(lastword $(subst /, ,$(DIR)))

insert_filter-output := $(DIR)insert_filter.stl
insert_filter-input := $(DIR)insert_filter.scad
insert_filter-flags :=

stl-target += insert_filter
