DIR := $(dir $(lastword $(MAKEFILE_LIST)))

threaded_shaft_foot-output := $(DIR)threaded_shaft_foot.stl
threaded_shaft_foot-input := $(DIR)threaded_shaft_foot.scad
threaded_shaft_foot-flags :=

stl-target += threaded_shaft_foot
