WALL_THICKNESS = 1.5;
LEDS_STRIP_THICKNESS = 6;
LED_STRIP_HEIGHT = 12;
COVER_SIZE = 15;

FIX_WIDTH = 8;

$fn = 30;

difference() {
    cube([LED_STRIP_HEIGHT + WALL_THICKNESS * 2, LEDS_STRIP_THICKNESS + WALL_THICKNESS * 2, COVER_SIZE + WALL_THICKNESS]);
    translate([WALL_THICKNESS, WALL_THICKNESS, 0]) cube([LED_STRIP_HEIGHT, LEDS_STRIP_THICKNESS, COVER_SIZE]);
    
}
