DIR := $(dir $(lastword $(MAKEFILE_LIST)))
TEST_NAME := $(lastword $(subst /, ,$(DIR)))

tube_splitter-output := $(DIR)tube_splitter.stl
tube_splitter-input := $(DIR)tube_splitter.scad
tube_splitter-flags :=

stl-target += tube_splitter
