DIR := $(dir $(lastword $(MAKEFILE_LIST)))
TEST_NAME := $(lastword $(subst /, ,$(DIR)))

bike_hook-output := $(DIR)bike_hook.stl
bike_hook-input := $(DIR)bike_hook.scad
bike_hook-flags :=

stl-target += bike_hook
